### ISSUE TITLE
Update configuration settings

### ISSUE THREAD

**Issue by TechSolomon** [acep-uaf/data-diode#37]
```yaml
# CLI Settings
input-diode:
  ip: "localhost"
  port: 49152
  timeout: 60 # seconds
output-diode:
  ip: "localhost"
  port: 13337
  tls: false
inside-mqtt:
  server: "localhost"
  port: 1883
  topic: "#"
outside-mqtt:
  server: "localhost"
  port: 1883
  topic-prefix: "" # Avoid namespace collisions

```
